--
-- PostgreSQL database dump
--

\restrict wztIMadaSxYxdens6af0zhaTYj5yxaVakz68DSS4IlqDlycb5WMUbOOSk5Bi6Nz

-- Dumped from database version 15.14 (Homebrew)
-- Dumped by pg_dump version 15.14 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS morse_code_db;
--
-- Name: morse_code_db; Type: DATABASE; Schema: -; Owner: aydgn
--

CREATE DATABASE morse_code_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF-8';


ALTER DATABASE morse_code_db OWNER TO aydgn;

\unrestrict wztIMadaSxYxdens6af0zhaTYj5yxaVakz68DSS4IlqDlycb5WMUbOOSk5Bi6Nz
\connect morse_code_db
\restrict wztIMadaSxYxdens6af0zhaTYj5yxaVakz68DSS4IlqDlycb5WMUbOOSk5Bi6Nz

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    criteria jsonb,
    description text,
    gem_reward integer NOT NULL,
    icon character varying(50),
    name character varying(100) NOT NULL,
    points integer NOT NULL,
    CONSTRAINT achievements_gem_reward_check CHECK ((gem_reward >= 0)),
    CONSTRAINT achievements_points_check CHECK ((points >= 0))
);


ALTER TABLE public.achievements OWNER TO morsemate;

--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    description text,
    display_order integer,
    icon_url character varying(255),
    is_active boolean NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.categories OWNER TO morsemate;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercise_attempts; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.exercise_attempts (
    id bigint NOT NULL,
    attempted_at timestamp(6) without time zone,
    is_correct boolean,
    points_earned integer NOT NULL,
    time_taken integer,
    user_answer text,
    exercise_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT exercise_attempts_time_taken_check CHECK ((time_taken >= 0))
);


ALTER TABLE public.exercise_attempts OWNER TO morsemate;

--
-- Name: exercise_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.exercise_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    correct_answer text NOT NULL,
    difficulty character varying(20),
    hint text,
    options jsonb,
    points integer NOT NULL,
    question text NOT NULL,
    time_limit integer,
    type character varying(50),
    lesson_id bigint NOT NULL,
    CONSTRAINT exercises_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[]))),
    CONSTRAINT exercises_type_check CHECK (((type)::text = ANY ((ARRAY['ENCODE'::character varying, 'DECODE'::character varying, 'AUDIO'::character varying, 'SPEED_TEST'::character varying, 'MULTI_CHOICE'::character varying])::text[])))
);


ALTER TABLE public.exercises OWNER TO morsemate;

--
-- Name: exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gem_transactions; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.gem_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    amount integer NOT NULL,
    description text,
    source character varying(100),
    transaction_type character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT gem_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['EARN'::character varying, 'SPEND'::character varying, 'PURCHASE'::character varying, 'REFUND'::character varying, 'BONUS'::character varying])::text[])))
);


ALTER TABLE public.gem_transactions OWNER TO morsemate;

--
-- Name: gem_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.gem_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gem_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessons; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    content text,
    description text,
    difficulty character varying(20),
    estimated_duration integer,
    order_index integer,
    points_reward integer NOT NULL,
    title character varying(200) NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT lessons_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[])))
);


ALTER TABLE public.lessons OWNER TO morsemate;

--
-- Name: lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3),
    metadata jsonb,
    payment_method character varying(50),
    status character varying(20),
    stripe_payment_id character varying(100),
    transaction_date timestamp(6) without time zone,
    subscription_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO morsemate;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: power_ups; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.power_ups (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    cost_gems integer NOT NULL,
    description text,
    duration_hours integer,
    icon character varying(50),
    is_active boolean NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    CONSTRAINT power_ups_cost_gems_check CHECK ((cost_gems >= 0)),
    CONSTRAINT power_ups_type_check CHECK (((type)::text = ANY ((ARRAY['XP_BOOST'::character varying, 'HEART_REFILL'::character varying, 'STREAK_FREEZE'::character varying, 'UNLIMITED_HEARTS'::character varying])::text[])))
);


ALTER TABLE public.power_ups OWNER TO morsemate;

--
-- Name: power_ups_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.power_ups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.power_ups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promo_codes; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.promo_codes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    applicable_plans jsonb,
    code character varying(50) NOT NULL,
    current_uses integer NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    is_active boolean NOT NULL,
    max_uses integer,
    valid_from timestamp(6) without time zone,
    valid_until timestamp(6) without time zone,
    CONSTRAINT promo_codes_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying])::text[])))
);


ALTER TABLE public.promo_codes OWNER TO morsemate;

--
-- Name: promo_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.promo_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promo_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_plans; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.subscription_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    billing_period character varying(20),
    daily_practice_limit integer,
    description text,
    features jsonb,
    is_active boolean NOT NULL,
    max_hearts integer NOT NULL,
    name character varying(50) NOT NULL,
    price numeric(10,2) NOT NULL,
    CONSTRAINT subscription_plans_billing_period_check CHECK (((billing_period)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying, 'LIFETIME'::character varying])::text[])))
);


ALTER TABLE public.subscription_plans OWNER TO morsemate;

--
-- Name: subscription_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.subscription_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_achievements; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.user_achievements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    earned_at timestamp(6) without time zone,
    achievement_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_achievements OWNER TO morsemate;

--
-- Name: user_achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.user_achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_gems; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.user_gems (
    id bigint NOT NULL,
    balance integer NOT NULL,
    last_updated timestamp(6) without time zone,
    total_earned integer NOT NULL,
    total_spent integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_gems_balance_check CHECK ((balance >= 0)),
    CONSTRAINT user_gems_total_earned_check CHECK ((total_earned >= 0)),
    CONSTRAINT user_gems_total_spent_check CHECK ((total_spent >= 0))
);


ALTER TABLE public.user_gems OWNER TO morsemate;

--
-- Name: user_gems_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.user_gems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_gems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_power_ups; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.user_power_ups (
    id bigint NOT NULL,
    activated_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    is_used boolean NOT NULL,
    purchased_at timestamp(6) without time zone,
    power_up_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_power_ups OWNER TO morsemate;

--
-- Name: user_power_ups_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.user_power_ups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_power_ups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_progress; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.user_progress (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    completed_at timestamp(6) without time zone,
    is_completed boolean NOT NULL,
    score integer,
    stars_earned integer,
    time_spent integer,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_progress_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT user_progress_check CHECK (((((stars_earned >= 0) AND (stars_earned <= 3)) AND (attempts >= 0) AND (time_spent IS NULL)) OR (time_spent >= 0))),
    CONSTRAINT user_progress_stars_earned_check CHECK (((stars_earned <= 3) AND (stars_earned >= 0)))
);


ALTER TABLE public.user_progress OWNER TO morsemate;

--
-- Name: user_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.user_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_subscriptions; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.user_subscriptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    auto_renew boolean NOT NULL,
    end_date timestamp(6) without time zone,
    next_billing_date timestamp(6) without time zone,
    start_date timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    stripe_subscription_id character varying(100),
    plan_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT user_subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying, 'PAUSED'::character varying])::text[])))
);


ALTER TABLE public.user_subscriptions OWNER TO morsemate;

--
-- Name: user_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.user_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: morsemate
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    current_streak integer NOT NULL,
    email character varying(100) NOT NULL,
    email_verified boolean NOT NULL,
    full_name character varying(100),
    hearts integer NOT NULL,
    is_active boolean NOT NULL,
    last_heart_refill timestamp(6) without time zone,
    last_login timestamp(6) without time zone,
    level integer NOT NULL,
    longest_streak integer NOT NULL,
    max_hearts integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    profile_picture_url character varying(255),
    total_points integer NOT NULL,
    username character varying(50) NOT NULL,
    role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    CONSTRAINT users_check CHECK (((hearts >= 0) AND (hearts <= max_hearts) AND (level >= 1))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'PREMIUM'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO morsemate;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: morsemate
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: achievements; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.achievements (id, created_at, updated_at, criteria, description, gem_reward, icon, name, points) FROM stdin;
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.categories (id, created_at, updated_at, description, display_order, icon_url, is_active, name) FROM stdin;
\.


--
-- Data for Name: exercise_attempts; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.exercise_attempts (id, attempted_at, is_correct, points_earned, time_taken, user_answer, exercise_id, user_id) FROM stdin;
\.


--
-- Data for Name: exercises; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.exercises (id, created_at, updated_at, correct_answer, difficulty, hint, options, points, question, time_limit, type, lesson_id) FROM stdin;
\.


--
-- Data for Name: gem_transactions; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.gem_transactions (id, created_at, updated_at, amount, description, source, transaction_type, user_id) FROM stdin;
\.


--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.lessons (id, created_at, updated_at, content, description, difficulty, estimated_duration, order_index, points_reward, title, category_id) FROM stdin;
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.payments (id, amount, currency, metadata, payment_method, status, stripe_payment_id, transaction_date, subscription_id, user_id) FROM stdin;
\.


--
-- Data for Name: power_ups; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.power_ups (id, created_at, updated_at, cost_gems, description, duration_hours, icon, is_active, name, type) FROM stdin;
\.


--
-- Data for Name: promo_codes; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.promo_codes (id, created_at, updated_at, applicable_plans, code, current_uses, discount_type, discount_value, is_active, max_uses, valid_from, valid_until) FROM stdin;
\.


--
-- Data for Name: subscription_plans; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.subscription_plans (id, created_at, updated_at, billing_period, daily_practice_limit, description, features, is_active, max_hearts, name, price) FROM stdin;
\.


--
-- Data for Name: user_achievements; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.user_achievements (id, created_at, updated_at, earned_at, achievement_id, user_id) FROM stdin;
\.


--
-- Data for Name: user_gems; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.user_gems (id, balance, last_updated, total_earned, total_spent, user_id) FROM stdin;
\.


--
-- Data for Name: user_power_ups; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.user_power_ups (id, activated_at, expires_at, is_active, is_used, purchased_at, power_up_id, user_id) FROM stdin;
\.


--
-- Data for Name: user_progress; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.user_progress (id, attempts, completed_at, is_completed, score, stars_earned, time_spent, lesson_id, user_id) FROM stdin;
\.


--
-- Data for Name: user_subscriptions; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.user_subscriptions (id, created_at, updated_at, auto_renew, end_date, next_billing_date, start_date, status, stripe_subscription_id, plan_id, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: morsemate
--

COPY public.users (id, created_at, updated_at, current_streak, email, email_verified, full_name, hearts, is_active, last_heart_refill, last_login, level, longest_streak, max_hearts, password_hash, profile_picture_url, total_points, username, role) FROM stdin;
2	2025-10-20 16:13:36.552633	2025-10-20 16:13:36.552588	0	mertaydogn01@gmail.com	f	Mert Aydogan	5	t	2025-10-20 16:13:36.552268	\N	1	0	5	$2a$10$VShVqy7mcBzbH2NYxeUUmeUCuwh.HcTMCD6TwHk3PE0sGoGpdniJy	\N	0	aydgn1	USER
1	2025-10-20 16:07:03.506383	2025-10-20 16:07:03.505791	0	mertaydogn0@gmail.com	f	Mert Aydogan	5	t	2025-10-20 16:07:03.488234	2025-10-20 16:16:12.074001	1	0	5	$2a$10$9CVkefy/YEyShWH0KDjBcuWajqHm40Y/lNVVFHCRi4xdlt8prPwH6	\N	0	aydgn	USER
3	2025-10-20 16:22:44.754145	2025-10-20 16:22:44.754106	0	mert@gmail.com	f	Mert Aydogan	5	t	2025-10-20 16:22:44.753817	2025-10-20 17:37:15.148533	1	0	5	$2a$10$ffpsGBGgBFKi5PZq2fzF8OzhZeBPRbhrwhCOtmFPQW7GC5FI.Cm5C	\N	0	john_de	USER
12	2025-10-20 17:44:39.275139	2025-10-20 17:44:39.274674	0	john@example1.com	f	Mert Aydogan	5	t	2025-10-20 17:44:39.265796	\N	1	0	5	$2a$10$VfuUl8V0nEHqG/q.AhH0C.cuVeCwrmDYcG4cfsDAlqGgxvcVziGI.	\N	0	joh1n_doe	USER
13	2025-10-20 17:51:35.302879	2025-10-20 17:52:22.543437	0	user1760971895183@test.com	f	Test User Updated	5	t	2025-10-20 17:51:35.302537	\N	1	0	5	$2a$10$rBAd.cdbx1IXbkzqguVBOeuWUuvTGJjF4Q.o7aBds3ZkiZyUWwgDW	https://example.com/avatar.jpg	0	user_1760971895183	USER
4	2025-10-20 16:23:20.698139	2025-10-20 16:23:20.698086	0	john@example.com	f	Mert Aydogan	5	t	2025-10-20 16:23:20.697742	2025-10-22 19:14:15.538385	1	0	5	$2a$10$L32S9p1cRsZN400YTfO/q.1lo.iUAT1sf9gK5WUT07PazHwSJ7ZGC	\N	0	john_doe	USER
\.


--
-- Name: achievements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.achievements_id_seq', 1, false);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: exercise_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.exercise_attempts_id_seq', 1, false);


--
-- Name: exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.exercises_id_seq', 1, false);


--
-- Name: gem_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.gem_transactions_id_seq', 1, false);


--
-- Name: lessons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.lessons_id_seq', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- Name: power_ups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.power_ups_id_seq', 1, false);


--
-- Name: promo_codes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.promo_codes_id_seq', 1, false);


--
-- Name: subscription_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.subscription_plans_id_seq', 1, false);


--
-- Name: user_achievements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.user_achievements_id_seq', 1, false);


--
-- Name: user_gems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.user_gems_id_seq', 1, false);


--
-- Name: user_power_ups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.user_power_ups_id_seq', 1, false);


--
-- Name: user_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.user_progress_id_seq', 1, false);


--
-- Name: user_subscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.user_subscriptions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: morsemate
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: exercise_attempts exercise_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.exercise_attempts
    ADD CONSTRAINT exercise_attempts_pkey PRIMARY KEY (id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);


--
-- Name: gem_transactions gem_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.gem_transactions
    ADD CONSTRAINT gem_transactions_pkey PRIMARY KEY (id);


--
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: power_ups power_ups_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.power_ups
    ADD CONSTRAINT power_ups_pkey PRIMARY KEY (id);


--
-- Name: promo_codes promo_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.promo_codes
    ADD CONSTRAINT promo_codes_pkey PRIMARY KEY (id);


--
-- Name: subscription_plans subscription_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: promo_codes uk_promo_codes_code; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.promo_codes
    ADD CONSTRAINT uk_promo_codes_code UNIQUE (code);


--
-- Name: user_achievements uk_user_achievements_user_achievement; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT uk_user_achievements_user_achievement UNIQUE (user_id, achievement_id);


--
-- Name: user_gems uk_user_gems_user; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_gems
    ADD CONSTRAINT uk_user_gems_user UNIQUE (user_id);


--
-- Name: user_progress uk_user_progress_user_lesson; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT uk_user_progress_user_lesson UNIQUE (user_id, lesson_id);


--
-- Name: user_subscriptions uka8455mp06snh8ry1uiy7s32d6; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT uka8455mp06snh8ry1uiy7s32d6 UNIQUE (user_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_achievements user_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (id);


--
-- Name: user_gems user_gems_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_gems
    ADD CONSTRAINT user_gems_pkey PRIMARY KEY (id);


--
-- Name: user_power_ups user_power_ups_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_power_ups
    ADD CONSTRAINT user_power_ups_pkey PRIMARY KEY (id);


--
-- Name: user_progress user_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_pkey PRIMARY KEY (id);


--
-- Name: user_subscriptions user_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_exercise_attempts_user; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_exercise_attempts_user ON public.exercise_attempts USING btree (user_id);


--
-- Name: idx_gem_transactions_user; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_gem_transactions_user ON public.gem_transactions USING btree (user_id);


--
-- Name: idx_payments_user; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_payments_user ON public.payments USING btree (user_id);


--
-- Name: idx_user_progress_lesson; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_user_progress_lesson ON public.user_progress USING btree (lesson_id);


--
-- Name: idx_user_progress_user; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_user_progress_user ON public.user_progress USING btree (user_id);


--
-- Name: idx_user_subscriptions_user; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_user_subscriptions_user ON public.user_subscriptions USING btree (user_id);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: morsemate
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: exercise_attempts exercise_attempts_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.exercise_attempts
    ADD CONSTRAINT exercise_attempts_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id);


--
-- Name: exercise_attempts exercise_attempts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.exercise_attempts
    ADD CONSTRAINT exercise_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: exercises exercises_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


--
-- Name: gem_transactions gem_transactions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.gem_transactions
    ADD CONSTRAINT gem_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: lessons lessons_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: payments payments_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id);


--
-- Name: payments payments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_achievements user_achievements_achievement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);


--
-- Name: user_achievements user_achievements_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_gems user_gems_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_gems
    ADD CONSTRAINT user_gems_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_power_ups user_power_ups_power_up_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_power_ups
    ADD CONSTRAINT user_power_ups_power_up_id_fkey FOREIGN KEY (power_up_id) REFERENCES public.power_ups(id);


--
-- Name: user_power_ups user_power_ups_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_power_ups
    ADD CONSTRAINT user_power_ups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_progress user_progress_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


--
-- Name: user_progress user_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_subscriptions user_subscriptions_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id);


--
-- Name: user_subscriptions user_subscriptions_user_id_key; Type: FK CONSTRAINT; Schema: public; Owner: morsemate
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_user_id_key FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: DATABASE morse_code_db; Type: ACL; Schema: -; Owner: aydgn
--

GRANT ALL ON DATABASE morse_code_db TO morsemate;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO morsemate;


--
-- PostgreSQL database dump complete
--

\unrestrict wztIMadaSxYxdens6af0zhaTYj5yxaVakz68DSS4IlqDlycb5WMUbOOSk5Bi6Nz

