spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:aydgn}
      password: ${SPRING_SECURITY_USER_PASSWORD:Aamert12}

logging:
  level:
    me.aydgn: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:MorseMate-Super-Secret-Key-For-Development-Only-Change-In-Production-2025}

stripe:
  api:
    key: "dummy-key"
